namespace FamilyRecipes.Models
{
    public class Ingredient
    {
        // Name, Type, Calories, Description
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public int Calories { get; set; } // per 100g
        public bool IsMeasuredByVolume { get; set; } // Helps selecting available measures
        public Ingredient() { }

        // Ingredient types are 
        public static List<string> GetIngredientTypes()
        {
            var ingredientTypes = new List<string> {
                // Animal products
                "Pork",
                "Beef",
                "Game",
                "Sheep",
                "Other Meat",
                "Poultry",
                "Fish",
                "Seafood",
                "Egg",
                "Dairy",
                // Grown products
                "Nut/Seed",
                "Bean/Legume",
                "Fruit/Berry",
                "Vegetable",
                "Wheat",
                "Grain",
                // Misc
                "Snack",
                "Beverage (Non-Alcoholic)",
                "Condiment",
                "Alcohol",
                "Other",
                // Basics
                "Baking",
                "Salt",
                "Sugar",
                "Water",
                "Oil",
                // Additives and Spices
                "Herb",
                "Spice",
                "Bullion",
                "Chemical",
                "Coloring",
                "Sweetener",
                "Flavor",
                "Essential Oil",
                "Extract",
                "Concentrate"
            };
            return ingredientTypes.OrderBy(s => s).ToList();
        }

        public static List<Ingredient> GetIngredients()
        {
            List<Ingredient> ingredients = new List<Ingredient>
            {
                new Ingredient { Name="Baking Powder", Calories=5, Type="Baking", IsMeasuredByVolume=true },
                new Ingredient { Name="Baking Soda", Calories=0, Type="Baking", IsMeasuredByVolume=true },
                new Ingredient { Name="Cocoa Powder", Calories=228, Type="Baking", IsMeasuredByVolume=true },
                new Ingredient { Name="Cornstarch", Calories=30, Type="Baking", IsMeasuredByVolume=true },
                new Ingredient { Name="Cream of Tartar", Calories=0, Type="Baking", IsMeasuredByVolume=true },
                new Ingredient { Name="Yeast (Active Dry)", Calories=21, Type="Baking", IsMeasuredByVolume=true },
                new Ingredient { Name="Vanilla Extract", Calories=12, Type="Baking", IsMeasuredByVolume=true },
                new Ingredient { Name="Molasses", Calories=58, Type="Baking", IsMeasuredByVolume=true },
                new Ingredient { Name="Honey", Calories=304, Type="Baking", IsMeasuredByVolume=true },
                new Ingredient { Name="Butter", Calories=102, Type="Baking", IsMeasuredByVolume=true },
                new Ingredient { Name="Flour (All-Purpose)", Calories=364, Type="Baking", IsMeasuredByVolume=true },
                new Ingredient { Name="Brown Sugar", Calories=380, Type="Baking", IsMeasuredByVolume=true },
                new Ingredient { Name="White Sugar", Calories=387, Type="Baking", IsMeasuredByVolume=true },
                new Ingredient { Name="Powdered Sugar", Calories=390, Type="Baking", IsMeasuredByVolume=true },
                new Ingredient { Name="Chocolate Chips", Calories=170, Type="Baking", IsMeasuredByVolume=true },
                new Ingredient { Name="Coconut Flakes", Calories=187, Type="Baking", IsMeasuredByVolume=true },
                new Ingredient { Name="Almond Flour", Calories=163, Type="Baking", IsMeasuredByVolume=true },
                new Ingredient { Name="Oatmeal", Calories=389, Type="Baking", IsMeasuredByVolume=true },
                new Ingredient { Name="Coconut Sugar", Calories=400, Type="Baking", IsMeasuredByVolume=true },
                new Ingredient { Name="Chia Seeds", Calories=137, Type="Baking", IsMeasuredByVolume=true },
                new Ingredient { Name="Ground Flaxseed", Calories=37, Type="Baking", IsMeasuredByVolume=true },
new Ingredient { Name="Unsweetened Cocoa Powder", Calories=12, Type="Baking", IsMeasuredByVolume=true },
                new Ingredient { Name="Pork Loin", Calories=242, Type="Pork", IsMeasuredByVolume=false },
                new Ingredient { Name="Pork Chops", Calories=231, Type="Pork", IsMeasuredByVolume=false },
                new Ingredient { Name="Pork Belly", Calories=518, Type="Pork", IsMeasuredByVolume=false },
                new Ingredient { Name="Spare Ribs", Calories=297, Type="Pork", IsMeasuredByVolume=false },
                new Ingredient { Name="Ground Pork", Calories=263, Type="Pork", IsMeasuredByVolume=false },
                new Ingredient { Name="Ham", Calories=145, Type="Pork", IsMeasuredByVolume=false },
                new Ingredient { Name="Bacon", Calories=541, Type="Pork", IsMeasuredByVolume=false },
                new Ingredient { Name="Pork Sausage", Calories=301, Type="Pork", IsMeasuredByVolume=false },
                new Ingredient { Name="Pork Tenderloin", Calories=143, Type="Pork", IsMeasuredByVolume=false },
                new Ingredient { Name="Pancetta", Calories=415, Type="Pork", IsMeasuredByVolume=false },
                new Ingredient { Name="Prosciutto", Calories=266, Type="Pork", IsMeasuredByVolume=false },
                new Ingredient { Name="Canadian Bacon", Calories=157, Type="Pork", IsMeasuredByVolume=false },
                new Ingredient { Name="Chorizo (Pork)", Calories=455, Type="Pork", IsMeasuredByVolume=false },
                new Ingredient { Name="Pork Cutlets", Calories=195, Type="Pork", IsMeasuredByVolume=false },
                new Ingredient { Name="Smoked Pork Shoulder", Calories=203, Type="Pork", IsMeasuredByVolume=false },
                new Ingredient { Name="Pork Cracklings", Calories=544, Type="Pork", IsMeasuredByVolume=false },
                new Ingredient { Name="Ground Beef", Calories=250, Type="Beef", IsMeasuredByVolume=false },
                new Ingredient { Name="Beef Sirloin", Calories=206, Type="Beef", IsMeasuredByVolume=false },
                new Ingredient { Name="Ribeye Steak", Calories=291, Type="Beef", IsMeasuredByVolume=false },
                new Ingredient { Name="Beef Tenderloin", Calories=175, Type="Beef", IsMeasuredByVolume=false },
                new Ingredient { Name="Chuck Roast", Calories=280, Type="Beef", IsMeasuredByVolume=false },
                new Ingredient { Name="Brisket", Calories=293, Type="Beef", IsMeasuredByVolume=false },
                new Ingredient { Name="Beef Short Ribs", Calories=212, Type="Beef", IsMeasuredByVolume=false },
                new Ingredient { Name="Beef Stew Meat", Calories=200, Type="Beef", IsMeasuredByVolume=false },
                new Ingredient { Name="Corned Beef", Calories=251, Type="Beef", IsMeasuredByVolume=false },
                new Ingredient { Name="Beef Jerky", Calories=410, Type="Beef", IsMeasuredByVolume=false },
                new Ingredient { Name="Beef Tri-Tip", Calories=215, Type="Beef", IsMeasuredByVolume=false },
                new Ingredient { Name="Beef Shank", Calories=196, Type="Beef", IsMeasuredByVolume=false },
                new Ingredient { Name="Beef Cheeks", Calories=213, Type="Beef", IsMeasuredByVolume=false },
                new Ingredient { Name="Oxtail", Calories=260, Type="Beef", IsMeasuredByVolume=false },
                new Ingredient { Name="Beef Marrow Bones", Calories=316, Type="Beef", IsMeasuredByVolume=false },
                new Ingredient { Name="Roast Beef", Calories=170, Type="Beef", IsMeasuredByVolume=false },
                new Ingredient { Name="Carpaccio (Beef)", Calories=150, Type="Beef", IsMeasuredByVolume=false },
                new Ingredient { Name="Beef Burgers", Calories=250, Type="Beef", IsMeasuredByVolume=false },
                new Ingredient { Name="Bresaola", Calories=151, Type="Beef", IsMeasuredByVolume=false },
                new Ingredient { Name="Venison Steak", Calories=158, Type="Game", IsMeasuredByVolume=false },
                new Ingredient { Name="Venison Loin", Calories=158, Type="Game", IsMeasuredByVolume=false },
                new Ingredient { Name="Wild Boar", Calories=191, Type="Game", IsMeasuredByVolume=false },
                new Ingredient { Name="Elk Steak", Calories=152, Type="Game", IsMeasuredByVolume=false },
                new Ingredient { Name="Rabbit", Calories=173, Type="Game", IsMeasuredByVolume=false },
                new Ingredient { Name="Pheasant", Calories=133, Type="Game", IsMeasuredByVolume=false },
                new Ingredient { Name="Duck (Wild)", Calories=337, Type="Game", IsMeasuredByVolume=false },
                new Ingredient { Name="Goose", Calories=305, Type="Game", IsMeasuredByVolume=false },
                new Ingredient { Name="Quail", Calories=123, Type="Game", IsMeasuredByVolume=false },
                new Ingredient { Name="Bison", Calories=143, Type="Game", IsMeasuredByVolume=false },
                new Ingredient { Name="Kangaroo", Calories=98, Type="Game", IsMeasuredByVolume=false },
                new Ingredient { Name="Moose Meat", Calories=133, Type="Game", IsMeasuredByVolume=false },
                new Ingredient { Name="Ostrich Meat", Calories=97, Type="Game", IsMeasuredByVolume=false },
                new Ingredient { Name="Squirrel", Calories=120, Type="Game", IsMeasuredByVolume=false },
                new Ingredient { Name="Partridge", Calories=135, Type="Game", IsMeasuredByVolume=false },
                new Ingredient { Name="Woodcock", Calories=230, Type="Game", IsMeasuredByVolume=false },
                new Ingredient { Name="Alligator Tail", Calories=143, Type="Other Meat", IsMeasuredByVolume=false },
                new Ingredient { Name="Frog Legs", Calories=73, Type="Other Meat", IsMeasuredByVolume=false },
                new Ingredient { Name="Snails (Escargot)", Calories=90, Type="Other Meat", IsMeasuredByVolume=false },
                new Ingredient { Name="Goat Meat", Calories=143, Type="Other Meat", IsMeasuredByVolume=false },
                new Ingredient { Name="Camel Meat", Calories=139, Type="Other Meat", IsMeasuredByVolume=false },
                new Ingredient { Name="Kangaroo Meat", Calories=98, Type="Other Meat", IsMeasuredByVolume=false },
                new Ingredient { Name="Python", Calories=133, Type="Other Meat", IsMeasuredByVolume=false },
                new Ingredient { Name="Crickets (Dried)", Calories=121, Type="Other Meat", IsMeasuredByVolume=false },
                new Ingredient { Name="Mealworms (Dried)", Calories=206, Type="Other Meat", IsMeasuredByVolume=false },
                new Ingredient { Name="Silkworm Pupae", Calories=154, Type="Other Meat", IsMeasuredByVolume=false },
                new Ingredient { Name="Grasshoppers", Calories=160, Type="Other Meat", IsMeasuredByVolume=false },
                new Ingredient { Name="Wild Hare", Calories=173, Type="Other Meat", IsMeasuredByVolume=false },
                new Ingredient { Name="Turkey Neck", Calories=189, Type="Other Meat", IsMeasuredByVolume=false },
                new Ingredient { Name="Beaver Tail", Calories=260, Type="Other Meat", IsMeasuredByVolume=false },
                new Ingredient { Name="Worms (Earthworms, Dried)", Calories=160, Type="Other Meat", IsMeasuredByVolume=false },
                new Ingredient { Name="Lamb Chops", Calories=291, Type="Sheep", IsMeasuredByVolume=false },
                new Ingredient { Name="Leg of Lamb", Calories=258, Type="Sheep", IsMeasuredByVolume=false },
                new Ingredient { Name="Ground Lamb", Calories=294, Type="Sheep", IsMeasuredByVolume=false },
                new Ingredient { Name="Mutton", Calories=234, Type="Sheep", IsMeasuredByVolume=false },
                new Ingredient { Name="Lamb Shoulder", Calories=236, Type="Sheep", IsMeasuredByVolume=false },
                new Ingredient { Name="Lamb Rack", Calories=292, Type="Sheep", IsMeasuredByVolume=false },
                new Ingredient { Name="Sheep's Liver", Calories=168, Type="Sheep", IsMeasuredByVolume=false },
                new Ingredient { Name="Lamb Shank", Calories=214, Type="Sheep", IsMeasuredByVolume=false },
                new Ingredient { Name="Lamb Kidney", Calories=103, Type="Sheep", IsMeasuredByVolume=false },
                new Ingredient { Name="Sheep Tripe", Calories=94, Type="Sheep", IsMeasuredByVolume=false },
                new Ingredient { Name="Lamb Brains", Calories=123, Type="Sheep", IsMeasuredByVolume=false },
                new Ingredient { Name="Sheep's Milk Cheese", Calories=340, Type="Sheep", IsMeasuredByVolume=false },
                new Ingredient { Name="Chicken Breast", Calories=165, Type="Poultry", IsMeasuredByVolume=false },
                new Ingredient { Name="Chicken Thigh", Calories=209, Type="Poultry", IsMeasuredByVolume=false },
                new Ingredient { Name="Chicken Wings", Calories=203, Type="Poultry", IsMeasuredByVolume=false },
                new Ingredient { Name="Whole Chicken", Calories=239, Type="Poultry", IsMeasuredByVolume=false },
                new Ingredient { Name="Turkey Breast", Calories=135, Type="Poultry", IsMeasuredByVolume=false },
                new Ingredient { Name="Duck Breast", Calories=337, Type="Poultry", IsMeasuredByVolume=false },
                new Ingredient { Name="Quail Meat", Calories=123, Type="Poultry", IsMeasuredByVolume=false },
                new Ingredient { Name="Pigeon (Squab)", Calories=142, Type="Poultry", IsMeasuredByVolume=false },
                new Ingredient { Name="Guinea Fowl", Calories=158, Type="Poultry", IsMeasuredByVolume=false },
                new Ingredient { Name="Goose Meat", Calories=305, Type="Poultry", IsMeasuredByVolume=false },
                new Ingredient { Name="Chicken Gizzards", Calories=94, Type="Poultry", IsMeasuredByVolume=false },
                new Ingredient { Name="Turkey Drumstick", Calories=170, Type="Poultry", IsMeasuredByVolume=false },
                new Ingredient { Name="Duck Legs", Calories=325, Type="Poultry", IsMeasuredByVolume=false },
                new Ingredient { Name="Chicken Liver", Calories=116, Type="Poultry", IsMeasuredByVolume=false },
                new Ingredient { Name="Turkey Bacon", Calories=218, Type="Poultry", IsMeasuredByVolume=false },
                new Ingredient { Name="Salmon", Calories=206, Type="Fish", IsMeasuredByVolume=false },
                new Ingredient { Name="Tuna (Fresh)", Calories=132, Type="Fish", IsMeasuredByVolume=false },
                new Ingredient { Name="Tuna (Canned, Water)", Calories=116, Type="Fish", IsMeasuredByVolume=false },
                new Ingredient { Name="Tuna (Canned, Oil)", Calories=191, Type="Fish", IsMeasuredByVolume=false },
                new Ingredient { Name="Cod", Calories=82, Type="Fish", IsMeasuredByVolume=false },
                new Ingredient { Name="Haddock", Calories=90, Type="Fish", IsMeasuredByVolume=false },
                new Ingredient { Name="Tilapia", Calories=96, Type="Fish", IsMeasuredByVolume=false },
                new Ingredient { Name="Halibut", Calories=111, Type="Fish", IsMeasuredByVolume=false },
                new Ingredient { Name="Mackerel", Calories=205, Type="Fish", IsMeasuredByVolume=false },
                new Ingredient { Name="Trout", Calories=168, Type="Fish", IsMeasuredByVolume=false },
                new Ingredient { Name="Swordfish", Calories=172, Type="Fish", IsMeasuredByVolume=false },
                new Ingredient { Name="Sea Bass", Calories=97, Type="Fish", IsMeasuredByVolume=false },
                new Ingredient { Name="Sardines", Calories=208, Type="Fish", IsMeasuredByVolume=false },
                new Ingredient { Name="Anchovies", Calories=131, Type="Fish", IsMeasuredByVolume=false },
                new Ingredient { Name="Snapper", Calories=100, Type="Fish", IsMeasuredByVolume=false },
                new Ingredient { Name="Catfish", Calories=105, Type="Fish", IsMeasuredByVolume=false },
                new Ingredient { Name="Eel", Calories=184, Type="Fish", IsMeasuredByVolume=false },
                new Ingredient { Name="Grouper", Calories=92, Type="Fish", IsMeasuredByVolume=false },
                new Ingredient { Name="Perch", Calories=94, Type="Fish", IsMeasuredByVolume=false },
                new Ingredient { Name="Shrimp", Calories=85, Type="Seafood", IsMeasuredByVolume=false },
                new Ingredient { Name="Lobster", Calories=89, Type="Seafood", IsMeasuredByVolume=false },
                new Ingredient { Name="Crab Meat", Calories=97, Type="Seafood", IsMeasuredByVolume=false },
                new Ingredient { Name="Clams", Calories=74, Type="Seafood", IsMeasuredByVolume=false },
                new Ingredient { Name="Mussels", Calories=172, Type="Seafood", IsMeasuredByVolume=false },
                new Ingredient { Name="Oysters", Calories=68, Type="Seafood", IsMeasuredByVolume=false },
                new Ingredient { Name="Scallops", Calories=111, Type="Seafood", IsMeasuredByVolume=false },
                new Ingredient { Name="Squid (Calamari)", Calories=92, Type="Seafood", IsMeasuredByVolume=false },
                new Ingredient { Name="Octopus", Calories=164, Type="Seafood", IsMeasuredByVolume=false },
                new Ingredient { Name="Abalone", Calories=105, Type="Seafood", IsMeasuredByVolume=false },
                new Ingredient { Name="Sea Urchin", Calories=82, Type="Seafood", IsMeasuredByVolume=false },
                new Ingredient { Name="Anchovy (Salted)", Calories=210, Type="Seafood", IsMeasuredByVolume=false },
                new Ingredient { Name="Caviar", Calories=264, Type="Seafood", IsMeasuredByVolume=false },
                new Ingredient { Name="Fish Roe", Calories=170, Type="Seafood", IsMeasuredByVolume=false },
                new Ingredient { Name="Langoustine", Calories=112, Type="Seafood", IsMeasuredByVolume=false },
                new Ingredient { Name="Chicken Egg", Calories=68, Type="Egg", IsMeasuredByVolume=false },
                new Ingredient { Name="Duck Egg", Calories=130, Type="Egg", IsMeasuredByVolume=false },
                new Ingredient { Name="Quail Egg", Calories=14, Type="Egg", IsMeasuredByVolume=false },
                new Ingredient { Name="Goose Egg", Calories=266, Type="Egg", IsMeasuredByVolume=false },
                new Ingredient { Name="Turkey Egg", Calories=135, Type="Egg", IsMeasuredByVolume=false },
                new Ingredient { Name="Ostrich Egg", Calories=2000, Type="Egg", IsMeasuredByVolume=false },
                new Ingredient { Name="Caviar (Fish Roe, Fresh)", Calories=264, Type="Egg", IsMeasuredByVolume=false },
                new Ingredient { Name="Fish Roe (Other)", Calories=170, Type="Egg", IsMeasuredByVolume=false },
                new Ingredient { Name="Salmon Roe", Calories=210, Type="Egg", IsMeasuredByVolume=false },
                new Ingredient { Name="Lobster Roe", Calories=95, Type="Egg", IsMeasuredByVolume=false },
                new Ingredient { Name="Milk (3% (Whole))", Calories=150, Type="Dairy", IsMeasuredByVolume=true },
                new Ingredient { Name="Milk (0.5% (Skim))", Calories=83, Type="Dairy", IsMeasuredByVolume=true },
                new Ingredient { Name="Milk (1.5%)", Calories=122, Type="Dairy", IsMeasuredByVolume=true },
                new Ingredient { Name="Butter", Calories=102, Type="Dairy", IsMeasuredByVolume=true },
                new Ingredient { Name="Cheddar Cheese", Calories=115, Type="Dairy", IsMeasuredByVolume=true },
                new Ingredient { Name="Mozzarella Cheese", Calories=280, Type="Dairy", IsMeasuredByVolume=true },
                new Ingredient { Name="Cream Cheese", Calories=342, Type="Dairy", IsMeasuredByVolume=true },
                new Ingredient { Name="Ricotta Cheese", Calories=300, Type="Dairy", IsMeasuredByVolume=true },
                new Ingredient { Name="Cottage Cheese", Calories=206, Type="Dairy", IsMeasuredByVolume=true },
                new Ingredient { Name="Greek Yogurt", Calories=59, Type="Dairy", IsMeasuredByVolume=true },
                new Ingredient { Name="Cream (Sour)", Calories=193, Type="Dairy", IsMeasuredByVolume=true },
                new Ingredient { Name="Cream (Heavy)", Calories=410, Type="Dairy", IsMeasuredByVolume=true },
                new Ingredient { Name="Ice Cream", Calories=207, Type="Dairy", IsMeasuredByVolume=true },
                new Ingredient { Name="Cream (Whipped)", Calories=52, Type="Dairy", IsMeasuredByVolume=true },
                new Ingredient { Name="Milk (Evaporated)", Calories=170, Type="Dairy", IsMeasuredByVolume=true },
                new Ingredient { Name="Milk (Condensed)", Calories=320, Type="Dairy", IsMeasuredByVolume=true },
                new Ingredient { Name="Milk (Lactose-Free)", Calories=130, Type="Dairy", IsMeasuredByVolume=true },
                new Ingredient { Name="Kefir", Calories=120, Type="Dairy", IsMeasuredByVolume=true },
                new Ingredient { Name="Ghee", Calories=112, Type="Dairy", IsMeasuredByVolume=true },
                new Ingredient { Name="Goat Milk", Calories=168, Type="Dairy", IsMeasuredByVolume=true },
                new Ingredient { Name="Goat Cheese", Calories=150, Type="Dairy", IsMeasuredByVolume=true },
                new Ingredient { Name="Blue Cheese", Calories=353, Type="Dairy", IsMeasuredByVolume=true },
                new Ingredient { Name="Parmesan Cheese", Calories=431, Type="Dairy", IsMeasuredByVolume=true },
                new Ingredient { Name="Feta Cheese", Calories=264, Type="Dairy", IsMeasuredByVolume=true },
                new Ingredient { Name="Swiss Cheese", Calories=380, Type="Dairy", IsMeasuredByVolume=true },
                new Ingredient { Name="Gruyère Cheese", Calories=413, Type="Dairy", IsMeasuredByVolume=true },
                new Ingredient { Name="Brie Cheese", Calories=334, Type="Dairy", IsMeasuredByVolume=true },
                new Ingredient { Name="Camembert Cheese", Calories=300, Type="Dairy", IsMeasuredByVolume=true },
                new Ingredient { Name="Bitter Cream", Calories=187, Type="Dairy", IsMeasuredByVolume=true },
                new Ingredient { Name="Clotted Cream", Calories=500, Type="Dairy", IsMeasuredByVolume=true },
                new Ingredient { Name="Almonds", Calories=579, Type="Nut/Seed", IsMeasuredByVolume=false },
                new Ingredient { Name="Cashews", Calories=553, Type="Nut/Seed", IsMeasuredByVolume=false },
                new Ingredient { Name="Walnuts", Calories=654, Type="Nut/Seed", IsMeasuredByVolume=false },
                new Ingredient { Name="Pistachios", Calories=562, Type="Nut/Seed", IsMeasuredByVolume=false },
                new Ingredient { Name="Pecans", Calories=691, Type="Nut/Seed", IsMeasuredByVolume=false },
                new Ingredient { Name="Macadamia Nuts", Calories=718, Type="Nut/Seed", IsMeasuredByVolume=false },
                new Ingredient { Name="Hazelnuts", Calories=628, Type="Nut/Seed", IsMeasuredByVolume=false },
                new Ingredient { Name="Brazil Nuts", Calories=659, Type="Nut/Seed", IsMeasuredByVolume=false },
                new Ingredient { Name="Chia Seeds", Calories=486, Type="Nut/Seed", IsMeasuredByVolume=false },
                new Ingredient { Name="Flaxseeds", Calories=534, Type="Nut/Seed", IsMeasuredByVolume=false },
                new Ingredient { Name="Sunflower Seeds", Calories=584, Type="Nut/Seed", IsMeasuredByVolume=false },
                new Ingredient { Name="Pumpkin Seeds", Calories=446, Type="Nut/Seed", IsMeasuredByVolume=false },
                new Ingredient { Name="Hemp Seeds", Calories=553, Type="Nut/Seed", IsMeasuredByVolume=false },
                new Ingredient { Name="Sesame Seeds", Calories=573, Type="Nut/Seed", IsMeasuredByVolume=false },
                new Ingredient { Name="Pine Nuts", Calories=673, Type="Nut/Seed", IsMeasuredByVolume=false },
                new Ingredient { Name="Coconut (Dried)", Calories=660, Type="Nut/Seed", IsMeasuredByVolume=false },
                new Ingredient { Name="Peanuts", Calories=567, Type="Nut/Seed", IsMeasuredByVolume=false },
                new Ingredient { Name="Sacha Inchi Seeds", Calories=570, Type="Nut/Seed", IsMeasuredByVolume=false },
                new Ingredient { Name="Black Beans", Calories=339, Type="Bean/Legume", IsMeasuredByVolume=false },
                new Ingredient { Name="Kidney Beans", Calories=333, Type="Bean/Legume", IsMeasuredByVolume=false },
                new Ingredient { Name="Chickpeas", Calories=364, Type="Bean/Legume", IsMeasuredByVolume=false },
                new Ingredient { Name="Lentils", Calories=353, Type="Bean/Legume", IsMeasuredByVolume=false },
                new Ingredient { Name="Pinto Beans", Calories=347, Type="Bean/Legume", IsMeasuredByVolume=false },
                new Ingredient { Name="Soybeans", Calories=446, Type="Bean/Legume", IsMeasuredByVolume=false },
                new Ingredient { Name="Green Beans", Calories=31, Type="Bean/Legume", IsMeasuredByVolume=false },
                new Ingredient { Name="Peas", Calories=81, Type="Bean/Legume", IsMeasuredByVolume=false },
                new Ingredient { Name="Fava Beans", Calories=341, Type="Bean/Legume", IsMeasuredByVolume=false },
                new Ingredient { Name="Navy Beans", Calories=337, Type="Bean/Legume", IsMeasuredByVolume=false },
                new Ingredient { Name="Black-eyed Peas", Calories=336, Type="Bean/Legume", IsMeasuredByVolume=false },
                new Ingredient { Name="Mung Beans", Calories=347, Type="Bean/Legume", IsMeasuredByVolume=false },
                new Ingredient { Name="Lima Beans", Calories=338, Type="Bean/Legume", IsMeasuredByVolume=false },
                new Ingredient { Name="Adzuki Beans", Calories=329, Type="Bean/Legume", IsMeasuredByVolume=false },
                new Ingredient { Name="Yellow Beans", Calories=341, Type="Bean/Legume", IsMeasuredByVolume=false },
                new Ingredient { Name="Cranberry Beans", Calories=337, Type="Bean/Legume", IsMeasuredByVolume=false },
                new Ingredient { Name="Green Lentils", Calories=360, Type="Bean/Legume", IsMeasuredByVolume=false },
                new Ingredient { Name="Apple", Calories=52, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Banana", Calories=89, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Strawberry", Calories=32, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Blueberry", Calories=57, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Raspberry", Calories=52, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Blackberry", Calories=43, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Grape", Calories=69, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Orange", Calories=47, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Lemon", Calories=29, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Pineapple", Calories=50, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Mango", Calories=60, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Peach", Calories=39, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Plum", Calories=46, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Pear", Calories=57, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Cherry", Calories=50, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Watermelon", Calories=30, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Kiwi", Calories=61, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Papaya", Calories=59, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Apricot", Calories=48, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Cantaloupe", Calories=34, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Black Currant", Calories=63, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Gooseberry", Calories=44, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Mulberry", Calories=43, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Red Currant", Calories=56, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Clementine", Calories=47, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Kumquat", Calories=71, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Mandarin Orange", Calories=53, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Pomelo", Calories=38, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Satsuma", Calories=47, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Tangerine", Calories=53, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Lime", Calories=30, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Blood Orange", Calories=47, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Rhubarb", Calories=21, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Elderberry", Calories=73, Type="Fruit/Berry", IsMeasuredByVolume=false },
                new Ingredient { Name="Mixed Vegetables", Calories=60, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Carrot", Calories=41, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Broccoli", Calories=55, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Spinach", Calories=23, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Cauliflower", Calories=25, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Lettuce", Calories=15, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Cucumber", Calories=16, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Tomato", Calories=18, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Potato", Calories=77, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Sweet Potato", Calories=86, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Onion", Calories=40, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Garlic", Calories=149, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Bell Pepper", Calories=20, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Zucchini", Calories=17, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Eggplant", Calories=25, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Mushrooms", Calories=22, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Peas", Calories=81, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Green Beans", Calories=31, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Asparagus", Calories=20, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Corn", Calories=96, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Beetroot", Calories=43, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Cabbage", Calories=25, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Brussels Sprouts", Calories=43, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Kale", Calories=49, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Artichoke", Calories=47, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Celery", Calories=16, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Leek", Calories=61, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Pumpkin", Calories=26, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Butternut Squash", Calories=45, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Rutabaga", Calories=37, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Radish", Calories=16, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Chard", Calories=19, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Arugula", Calories=25, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Okra", Calories=33, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Fennel", Calories=31, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Chili Pepper", Calories=40, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Scallions", Calories=32, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Ginger", Calories=80, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Yam", Calories=118, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Bamboo Shoots", Calories=14, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Taro", Calories=142, Type="Vegetable", IsMeasuredByVolume=false },
                new Ingredient { Name="Flour", Calories=364, Type="Wheat", IsMeasuredByVolume=true },
                new Ingredient { Name="Wheat", Calories=339, Type="Wheat/Grain", IsMeasuredByVolume=false },
                new Ingredient { Name="Rice (White)", Calories=130, Type="Wheat/Grain", IsMeasuredByVolume=false },
                new Ingredient { Name="Rice (Brown)", Calories=111, Type="Grain", IsMeasuredByVolume=false },
                new Ingredient { Name="Oats", Calories=389, Type="Wheat/Grain", IsMeasuredByVolume=false },
                new Ingredient { Name="Barley", Calories=354, Type="Wheat/Grain", IsMeasuredByVolume=false },
                new Ingredient { Name="Cornmeal", Calories=342, Type="Wheat/Grain", IsMeasuredByVolume=false },
                new Ingredient { Name="Rye", Calories=338, Type="Wheat/Grain", IsMeasuredByVolume=false },
                new Ingredient { Name="Quinoa", Calories=120, Type="Wheat/Grain", IsMeasuredByVolume=false },
                new Ingredient { Name="Buckwheat", Calories=343, Type="Wheat/Grain", IsMeasuredByVolume=false },
                new Ingredient { Name="Millet", Calories=378, Type="Wheat/Grain", IsMeasuredByVolume=false },
                new Ingredient { Name="Amaranth", Calories=371, Type="Wheat/Grain", IsMeasuredByVolume=false },
                new Ingredient { Name="Spelt", Calories=338, Type="Wheat/Grain", IsMeasuredByVolume=false },
                new Ingredient { Name="Farro", Calories=340, Type="Wheat/Grain", IsMeasuredByVolume=false },
                new Ingredient { Name="Triticale", Calories=336, Type="Wheat/Grain", IsMeasuredByVolume=false },
                new Ingredient { Name="Teff", Calories=367, Type="Wheat/Grain", IsMeasuredByVolume=false },
                new Ingredient { Name="Freekeh", Calories=337, Type="Wheat/Grain", IsMeasuredByVolume=false },
                new Ingredient { Name="Sorghum", Calories=329, Type="Wheat/Grain", IsMeasuredByVolume=false },
                new Ingredient { Name="Bulgur", Calories=342, Type="Wheat/Grain", IsMeasuredByVolume=false },
                new Ingredient { Name="Kamut", Calories=337, Type="Wheat/Grain", IsMeasuredByVolume=false },
                new Ingredient { Name="Chips", Calories=150, Type="Snack", IsMeasuredByVolume=false },
                new Ingredient { Name="Popcorn", Calories=387, Type="Snack", IsMeasuredByVolume=false },
                new Ingredient { Name="Pretzels", Calories=380, Type="Snack", IsMeasuredByVolume=false },
                new Ingredient { Name="Granola Bar", Calories=200, Type="Snack", IsMeasuredByVolume=false },
                new Ingredient { Name="Rice Cake", Calories=35, Type="Snack", IsMeasuredByVolume=false },
                new Ingredient { Name="Trail Mix", Calories=500, Type="Snack", IsMeasuredByVolume=false },
                new Ingredient { Name="Cookies", Calories=200, Type="Snack", IsMeasuredByVolume=false },
                new Ingredient { Name="Candy", Calories=150, Type="Snack", IsMeasuredByVolume=false },
                new Ingredient { Name="Chocolate", Calories=150, Type="Snack", IsMeasuredByVolume=false },
                new Ingredient { Name="Nuts", Calories=200, Type="Snack", IsMeasuredByVolume=false },
                new Ingredient { Name="Dried Fruit", Calories=300, Type="Snack", IsMeasuredByVolume=false },
                new Ingredient { Name="Granola", Calories=150, Type="Snack", IsMeasuredByVolume=false },
                new Ingredient { Name="Fruit Snacks", Calories=100, Type="Snack", IsMeasuredByVolume=false },
                new Ingredient { Name="Cheese Sticks", Calories=80, Type="Snack", IsMeasuredByVolume=false },
                new Ingredient { Name="Yogurt", Calories=59, Type="Snack", IsMeasuredByVolume=true },
                new Ingredient { Name="Ice Cream", Calories=207, Type="Snack", IsMeasuredByVolume=true },
                new Ingredient { Name="Rice Crackers", Calories=100, Type="Snack", IsMeasuredByVolume=false },
                new Ingredient { Name="Beef Jerky", Calories=250, Type="Snack", IsMeasuredByVolume=false },
                new Ingredient { Name="Cheese Crackers", Calories=150, Type="Snack", IsMeasuredByVolume=false },
                new Ingredient { Name="Energy Bar", Calories=250, Type="Snack", IsMeasuredByVolume=false },
                new Ingredient { Name="Apple Slices", Calories=52, Type="Snack", IsMeasuredByVolume=false },
                new Ingredient { Name="Banana Chips", Calories=150, Type="Snack", IsMeasuredByVolume=false },
                new Ingredient { Name="Peanut Butter Cups", Calories=350, Type="Snack", IsMeasuredByVolume=false },
                new Ingredient { Name="Fruit Chips", Calories=130, Type="Snack", IsMeasuredByVolume=false },
                new Ingredient { Name="Hummus and Veggies", Calories=200, Type="Snack", IsMeasuredByVolume=false },
                new Ingredient { Name="Water", Calories=0, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Coffee", Calories=2, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Tea", Calories=2, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Orange Juice", Calories=45, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Apple Juice", Calories=52, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Lemonade", Calories=53, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Milk", Calories=42, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Soy Milk", Calories=33, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Almond Milk", Calories=17, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Coconut Water", Calories=19, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Vegetable Juice", Calories=40, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Iced Tea", Calories=30, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Sparkling Water", Calories=0, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Smoothie", Calories=150, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Hot Chocolate", Calories=190, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Fruit Punch", Calories=100, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Milkshake", Calories=250, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Kombucha", Calories=30, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Lassi", Calories=150, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Herbal Tea", Calories=2, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Soda (Cola)", Calories=150, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Lemonade", Calories=100, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Soda (Orange)", Calories=160, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Soda (Root Beer)", Calories=170, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Soda (Ginger Ale)", Calories=125, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Soda (Lemon-Lime)", Calories=140, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Tonic Water", Calories=120, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Energy Drink (Generic)", Calories=110, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Energy Drink (Red Bull)", Calories=110, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Energy Drink (Monster)", Calories=160, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Soda (Cola Zero)", Calories=0, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Soda (Diet Pepsi)", Calories=0, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Soda (Pear)", Calories=140, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Soda (Raspberry)", Calories=150, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Soda (Generic)", Calories=150, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Soda (Fruit)", Calories=150, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Soda (Sugar)", Calories=150, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Grenadine", Calories=70, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Fruit Juice", Calories=45, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Iced Coffee", Calories=50, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Coconut Milk", Calories=45, Type="Beverage (Non-Alcoholic)", IsMeasuredByVolume=true },
                new Ingredient { Name="Ketchup", Calories=15, Type="Condiment", IsMeasuredByVolume=true },
                new Ingredient { Name="Mustard", Calories=3, Type="Condiment", IsMeasuredByVolume=true },
                new Ingredient { Name="Mayonnaise", Calories=94, Type="Condiment", IsMeasuredByVolume=true },
                new Ingredient { Name="Hot Sauce", Calories=0, Type="Condiment", IsMeasuredByVolume=true },
                new Ingredient { Name="Soy Sauce", Calories=10, Type="Condiment", IsMeasuredByVolume=true },
                new Ingredient { Name="Barbecue Sauce", Calories=70, Type="Condiment", IsMeasuredByVolume=true },
                new Ingredient { Name="Sriracha", Calories=15, Type="Condiment", IsMeasuredByVolume=true },
                new Ingredient { Name="Vinegar", Calories=0, Type="Condiment", IsMeasuredByVolume=true },
                new Ingredient { Name="Relish", Calories=20, Type="Condiment", IsMeasuredByVolume=true },
                new Ingredient { Name="Tartar Sauce", Calories=70, Type="Condiment", IsMeasuredByVolume=true },
                new Ingredient { Name="Salad Dressing", Calories=100, Type="Condiment", IsMeasuredByVolume=true },
                new Ingredient { Name="Ranch Dressing", Calories=145, Type="Condiment", IsMeasuredByVolume=true },
                new Ingredient { Name="Honey", Calories=64, Type="Condiment", IsMeasuredByVolume=true },
                new Ingredient { Name="Maple Syrup", Calories=52, Type="Condiment", IsMeasuredByVolume=true },
                new Ingredient { Name="Worcestershire Sauce", Calories=13, Type="Condiment", IsMeasuredByVolume=true },
                new Ingredient { Name="Pesto", Calories=200, Type="Condiment", IsMeasuredByVolume=true },
                new Ingredient { Name="Olive Oil", Calories=119, Type="Condiment", IsMeasuredByVolume=true },
                new Ingredient { Name="Balsamic Vinegar", Calories=14, Type="Condiment", IsMeasuredByVolume=true },
                new Ingredient { Name="Garlic Butter", Calories=102, Type="Condiment", IsMeasuredByVolume=true },
                new Ingredient { Name="Chili Paste", Calories=60, Type="Condiment", IsMeasuredByVolume=true },
                new Ingredient { Name="Tahini", Calories=89, Type="Condiment", IsMeasuredByVolume=true },
                new Ingredient { Name="Poppy Seed Dressing", Calories=140, Type="Condiment", IsMeasuredByVolume=true },
                new Ingredient { Name="Fish Sauce", Calories=10, Type="Condiment", IsMeasuredByVolume=true },
                new Ingredient { Name="Lemon Juice", Calories=4, Type="Condiment", IsMeasuredByVolume=true },
                new Ingredient { Name="Sweet-and-Sour Sauce", Calories=60, Type="Condiment", IsMeasuredByVolume=true },
                new Ingredient { Name="Black-Pepper Sauce", Calories=25, Type="Condiment", IsMeasuredByVolume=true },
                new Ingredient { Name="Marinade (Generic)", Calories=50, Type="Condiment", IsMeasuredByVolume=true },
                new Ingredient { Name="Oyster Sauce", Calories=9, Type="Condiment", IsMeasuredByVolume=true },
                new Ingredient { Name="Beer", Calories=150, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Vodka", Calories=96, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Whiskey", Calories=105, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Rum", Calories=97, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Tequila", Calories=98, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Gin", Calories=110, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Brandy", Calories=100, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Champagne", Calories=80, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Cider", Calories=160, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Liqueur", Calories=160, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Absinthe", Calories=120, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Port Wine", Calories=160, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Sherry", Calories=120, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Sake", Calories=120, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Baijiu", Calories=130, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Mead", Calories=150, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Cocktail", Calories=200, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Mojito", Calories=180, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Martini", Calories=220, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Bloody Mary", Calories=150, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Long Island Iced Tea", Calories=250, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Wine (White)", Calories=120, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Wine (Red)", Calories=125, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Wine (Sparkling)", Calories=80, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Amaretto", Calories=160, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Baileys Irish Cream", Calories=140, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Cointreau", Calories=100, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Grand Marnier", Calories=103, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Kahlúa", Calories=152, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Midori", Calories=112, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Jägermeister", Calories=134, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Disaronno", Calories=160, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Sambuca", Calories=180, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Chartreuse", Calories=138, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Limoncello", Calories=175, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Creme de Menthe", Calories=152, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Pimm's No. 1", Calories=170, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Beer (Lager)", Calories=150, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Beer (Pilsner)", Calories=140, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Beer (Porter)", Calories=180, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Beer (Stout)", Calories=190, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Beer (Pale Ale)", Calories=175, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Beer (Ale)", Calories=160, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Beer (IPA)", Calories=210, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Beer (Draught)", Calories=150, Type="Alcohol", IsMeasuredByVolume=true },
                new Ingredient { Name="Table Salt", Calories=0, Type="Salt", IsMeasuredByVolume=true },
                new Ingredient { Name="Sea Salt", Calories=0, Type="Salt", IsMeasuredByVolume=true },
                new Ingredient { Name="Himalayan Pink Salt", Calories=0, Type="Salt", IsMeasuredByVolume=true },
                new Ingredient { Name="Kosher Salt", Calories=0, Type="Salt", IsMeasuredByVolume=true },
                new Ingredient { Name="Celtic Sea Salt", Calories=0, Type="Salt", IsMeasuredByVolume=true },
                new Ingredient { Name="Fleur de Sel", Calories=0, Type="Salt", IsMeasuredByVolume=true },
                new Ingredient { Name="Flavored Salt", Calories=0, Type="Salt", IsMeasuredByVolume=true },
                new Ingredient { Name="Garlic Salt", Calories=0, Type="Salt", IsMeasuredByVolume=true },
                new Ingredient { Name="Onion Salt", Calories=0, Type="Salt", IsMeasuredByVolume=true },
                new Ingredient { Name="Black Salt (Kala Namak)", Calories=0, Type="Salt", IsMeasuredByVolume=true },
                new Ingredient { Name="Pink Himalayan Salt (Coarse)", Calories=0, Type="Salt", IsMeasuredByVolume=true },
                new Ingredient { Name="Smoked Salt", Calories=0, Type="Salt", IsMeasuredByVolume=true },
                new Ingredient { Name="Granulated Sugar", Calories=387, Type="Sugar", IsMeasuredByVolume=true },
                new Ingredient { Name="Brown Sugar", Calories=380, Type="Sugar", IsMeasuredByVolume=true },
                new Ingredient { Name="Powdered Sugar", Calories=389, Type="Sugar", IsMeasuredByVolume=true },
                new Ingredient { Name="Raw Sugar", Calories=380, Type="Sugar", IsMeasuredByVolume=true },
                new Ingredient { Name="Coconut Sugar", Calories=375, Type="Sugar", IsMeasuredByVolume=true },
                new Ingredient { Name="Turbinado Sugar", Calories=375, Type="Sugar", IsMeasuredByVolume=true },
                new Ingredient { Name="Maple Sugar", Calories=380, Type="Sugar", IsMeasuredByVolume=true },
                new Ingredient { Name="Palm Sugar", Calories=375, Type="Sugar", IsMeasuredByVolume=true },
                new Ingredient { Name="Honey", Calories=304, Type="Sugar", IsMeasuredByVolume=true },
                new Ingredient { Name="Agave Syrup", Calories=310, Type="Sugar", IsMeasuredByVolume=true },
                new Ingredient { Name="Stevia", Calories=0, Type="Sugar", IsMeasuredByVolume=true },
                new Ingredient { Name="Molasses", Calories=290, Type="Sugar", IsMeasuredByVolume=true },
                new Ingredient { Name="Corn Syrup", Calories=260, Type="Sugar", IsMeasuredByVolume=true },
                new Ingredient { Name="High-Fructose Corn Syrup", Calories=300, Type="Sugar", IsMeasuredByVolume=true },
                new Ingredient { Name="Maple Syrup", Calories=260, Type="Sugar", IsMeasuredByVolume=true },
                new Ingredient { Name="Date Sugar", Calories=370, Type="Sugar", IsMeasuredByVolume=true },
                new Ingredient { Name="Birch-sugar (Xylitol)", Calories=240, Type="Sugar", IsMeasuredByVolume=true },
                new Ingredient { Name="Dextrose", Calories=365, Type="Sugar", IsMeasuredByVolume=true },
                new Ingredient { Name="Fructose", Calories=400, Type="Sugar", IsMeasuredByVolume=true },
                new Ingredient { Name="Tap Water", Calories=0, Type="Water", IsMeasuredByVolume=true },
                new Ingredient { Name="Spring Water", Calories=0, Type="Water", IsMeasuredByVolume=true },
                new Ingredient { Name="Mineral Water", Calories=0, Type="Water", IsMeasuredByVolume=true },
                new Ingredient { Name="Distilled Water", Calories=0, Type="Water", IsMeasuredByVolume=true },
                new Ingredient { Name="Filtered Water", Calories=0, Type="Water", IsMeasuredByVolume=true },
                new Ingredient { Name="Alkaline Water", Calories=0, Type="Water", IsMeasuredByVolume=true },
                new Ingredient { Name="Sparkling Water", Calories=0, Type="Water", IsMeasuredByVolume=true },
                new Ingredient { Name="Coconut Water", Calories=46, Type="Water", IsMeasuredByVolume=true },
                new Ingredient { Name="Flavored Water", Calories=10, Type="Water", IsMeasuredByVolume=true },
                new Ingredient { Name="Ice", Calories=0, Type="Water", IsMeasuredByVolume=true },
                new Ingredient { Name="Olive Oil", Calories=119, Type="Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Vegetable Oil", Calories=120, Type="Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Canola Oil", Calories=124, Type="Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Sunflower Oil", Calories=120, Type="Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Coconut Oil", Calories=117, Type="Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Avocado Oil", Calories=120, Type="Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Peanut Oil", Calories=120, Type="Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Sesame Oil", Calories=120, Type="Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Grapeseed Oil", Calories=120, Type="Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Almond Oil", Calories=120, Type="Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Walnut Oil", Calories=120, Type="Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Flaxseed Oil", Calories=120, Type="Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Truffle Oil", Calories=120, Type="Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Hazelnut Oil", Calories=120, Type="Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Pumpkin Seed Oil", Calories=120, Type="Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Rapeseed Oil", Calories=120, Type="Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Basil", Calories=1, Type="Herb", IsMeasuredByVolume=false },
                new Ingredient { Name="Oregano", Calories=1, Type="Herb", IsMeasuredByVolume=false },
                new Ingredient { Name="Thyme", Calories=1, Type="Herb", IsMeasuredByVolume=false },
                new Ingredient { Name="Rosemary", Calories=1, Type="Herb", IsMeasuredByVolume=false },
                new Ingredient { Name="Parsley", Calories=1, Type="Herb", IsMeasuredByVolume=false },
                new Ingredient { Name="Cilantro", Calories=1, Type="Herb", IsMeasuredByVolume=false },
                new Ingredient { Name="Mint", Calories=1, Type="Herb", IsMeasuredByVolume=false },
                new Ingredient { Name="Sage", Calories=1, Type="Herb", IsMeasuredByVolume=false },
                new Ingredient { Name="Dill", Calories=1, Type="Herb", IsMeasuredByVolume=false },
                new Ingredient { Name="Tarragon", Calories=1, Type="Herb", IsMeasuredByVolume=false },
                new Ingredient { Name="Chives", Calories=1, Type="Herb", IsMeasuredByVolume=false },
                new Ingredient { Name="Bay Leaves", Calories=2, Type="Herb", IsMeasuredByVolume=false },
                new Ingredient { Name="Lavender", Calories=2, Type="Herb", IsMeasuredByVolume=false },
                new Ingredient { Name="Marjoram", Calories=1, Type="Herb", IsMeasuredByVolume=false },
                new Ingredient { Name="Chervil", Calories=1, Type="Herb", IsMeasuredByVolume=false },
                new Ingredient { Name="Fennel Fronds", Calories=1, Type="Herb", IsMeasuredByVolume=false },
                new Ingredient { Name="Chicken Bullion Cube", Calories=10, Type="Bullion", IsMeasuredByVolume=false },
                new Ingredient { Name="Beef Bullion Cube", Calories=15, Type="Bullion", IsMeasuredByVolume=false },
                new Ingredient { Name="Vegetable Bullion Cube", Calories=5, Type="Bullion", IsMeasuredByVolume=false },
                new Ingredient { Name="Fish Bullion Cube", Calories=10, Type="Bullion", IsMeasuredByVolume=false },
                new Ingredient { Name="Chicken Stock", Calories=40, Type="Bullion", IsMeasuredByVolume=true },
                new Ingredient { Name="Beef Stock", Calories=50, Type="Bullion", IsMeasuredByVolume=true },
                new Ingredient { Name="Vegetable Stock", Calories=30, Type="Bullion", IsMeasuredByVolume=true },
                new Ingredient { Name="Mushroom Stock", Calories=40, Type="Bullion", IsMeasuredByVolume=true },
                new Ingredient { Name="Bone Broth (Chicken)", Calories=35, Type="Bullion", IsMeasuredByVolume=true },
                new Ingredient { Name="Bone Broth (Beef)", Calories=45, Type="Bullion", IsMeasuredByVolume=true },
                new Ingredient { Name="Instant Stock Powder", Calories=20, Type="Bullion", IsMeasuredByVolume=true },
                new Ingredient { Name="Bouillon Granules", Calories=15, Type="Bullion", IsMeasuredByVolume=true },
                new Ingredient { Name="Baking Soda", Calories=0, Type="Chemical", IsMeasuredByVolume=true },
                new Ingredient { Name="Baking Powder", Calories=6, Type="Chemical", IsMeasuredByVolume=true },
                new Ingredient { Name="Cornstarch", Calories=30, Type="Chemical", IsMeasuredByVolume=true },
                new Ingredient { Name="Cream of Tartar", Calories=0, Type="Chemical", IsMeasuredByVolume=true },
                new Ingredient { Name="Ascorbic Acid", Calories=0, Type="Chemical", IsMeasuredByVolume=true },
                new Ingredient { Name="Citric Acid", Calories=0, Type="Chemical", IsMeasuredByVolume=true },
                new Ingredient { Name="Sodium Bicarbonate", Calories=0, Type="Chemical", IsMeasuredByVolume=true },
                new Ingredient { Name="Xanthan Gum", Calories=7, Type="Chemical", IsMeasuredByVolume=true },
                new Ingredient { Name="Guar Gum", Calories=5, Type="Chemical", IsMeasuredByVolume=true },
                new Ingredient { Name="Gelatin", Calories=23, Type="Chemical", IsMeasuredByVolume=true },
                new Ingredient { Name="Pectin", Calories=5, Type="Chemical", IsMeasuredByVolume=true },
                new Ingredient { Name="Lecithin", Calories=90, Type="Chemical", IsMeasuredByVolume=true },
                new Ingredient { Name="Sodium Alginate", Calories=0, Type="Chemical", IsMeasuredByVolume=true },
                new Ingredient { Name="Calcium Chloride", Calories=0, Type="Chemical", IsMeasuredByVolume=true },
                new Ingredient { Name="Magnesium Sulfate", Calories=0, Type="Chemical", IsMeasuredByVolume=true },
                new Ingredient { Name="Tapioca Starch", Calories=30, Type="Chemical", IsMeasuredByVolume=true },
                new Ingredient { Name="Amylase", Calories=0, Type="Chemical", IsMeasuredByVolume=true },
                new Ingredient { Name="Caramel Coloring", Calories=0, Type="Coloring", IsMeasuredByVolume=true },
                new Ingredient { Name="Beet Juice Powder", Calories=20, Type="Coloring", IsMeasuredByVolume=true },
                new Ingredient { Name="Turmeric", Calories=1, Type="Coloring", IsMeasuredByVolume=false },
                new Ingredient { Name="Spirulina", Calories=2, Type="Coloring", IsMeasuredByVolume=false },
                new Ingredient { Name="Annatto", Calories=3, Type="Coloring", IsMeasuredByVolume=true },
                new Ingredient { Name="Red 40 (Allura Red)", Calories=0, Type="Coloring", IsMeasuredByVolume=true },
                new Ingredient { Name="Yellow 5 (Tartrazine)", Calories=0, Type="Coloring", IsMeasuredByVolume=true },
                new Ingredient { Name="Blue 1 (Brilliant Blue)", Calories=0, Type="Coloring", IsMeasuredByVolume=true },
                new Ingredient { Name="Green 3 (Fast Green)", Calories=0, Type="Coloring", IsMeasuredByVolume=true },
                new Ingredient { Name="Cochineal (Carmine)", Calories=0, Type="Coloring", IsMeasuredByVolume=true },
                new Ingredient { Name="Red 3 (Erythrosine)", Calories=0, Type="Coloring", IsMeasuredByVolume=true },
                new Ingredient { Name="Purple Yam (Ube)", Calories=3, Type="Coloring", IsMeasuredByVolume=true },
                new Ingredient { Name="Matcha Powder", Calories=3, Type="Coloring", IsMeasuredByVolume=true },
                new Ingredient { Name="Black Carrot Extract", Calories=10, Type="Coloring", IsMeasuredByVolume=true },
                new Ingredient { Name="Charcoal Powder", Calories=2, Type="Coloring", IsMeasuredByVolume=true },
                new Ingredient { Name="Indigo", Calories=0, Type="Coloring", IsMeasuredByVolume=true },
                new Ingredient { Name="Honey", Calories=64, Type="Sweetener", IsMeasuredByVolume=true },
                new Ingredient { Name="Maple Syrup", Calories=52, Type="Sweetener", IsMeasuredByVolume=true },
                new Ingredient { Name="Agave Syrup", Calories=60, Type="Sweetener", IsMeasuredByVolume=true },
                new Ingredient { Name="Stevia", Calories=0, Type="Sweetener", IsMeasuredByVolume=true },
                new Ingredient { Name="Molasses", Calories=58, Type="Sweetener", IsMeasuredByVolume=true },
                new Ingredient { Name="Coconut Sugar", Calories=38, Type="Sweetener", IsMeasuredByVolume=true },
                new Ingredient { Name="Date Syrup", Calories=277, Type="Sweetener", IsMeasuredByVolume=true },
                new Ingredient { Name="Aspartame (E951)", Calories=4, Type="Sweetener", IsMeasuredByVolume=true },
                new Ingredient { Name="Saccharin (E954)", Calories=0, Type="Sweetener", IsMeasuredByVolume=true },
                new Ingredient { Name="Sucralose (E955)", Calories=0, Type="Sweetener", IsMeasuredByVolume=true },
                new Ingredient { Name="Steviol Glycosides (E960)", Calories=0, Type="Sweetener", IsMeasuredByVolume=true },
                new Ingredient { Name="Acesulfame K (E950)", Calories=0, Type="Sweetener", IsMeasuredByVolume=true },
                new Ingredient { Name="Cyclamate (E952)", Calories=0, Type="Sweetener", IsMeasuredByVolume=true },
                new Ingredient { Name="Sorbitol (E420)", Calories=3, Type="Sweetener", IsMeasuredByVolume=true },
                new Ingredient { Name="Xylitol (E967)", Calories=2, Type="Sweetener", IsMeasuredByVolume=true },
                new Ingredient { Name="Maltitol (E965)", Calories=2, Type="Sweetener", IsMeasuredByVolume=true },
                new Ingredient { Name="Erythritol (E968)", Calories=0, Type="Sweetener", IsMeasuredByVolume=true },
                new Ingredient { Name="Vanilla (Artificial)", Calories=0, Type="Flavor", IsMeasuredByVolume=true },
                new Ingredient { Name="Cinnamon", Calories=6, Type="Flavor", IsMeasuredByVolume=true },
                new Ingredient { Name="Ginger", Calories=5, Type="Flavor", IsMeasuredByVolume=true },
                new Ingredient { Name="Clove", Calories=6, Type="Flavor", IsMeasuredByVolume=true },
                new Ingredient { Name="Nutmeg", Calories=6, Type="Flavor", IsMeasuredByVolume=true },
                new Ingredient { Name="Allspice", Calories=6, Type="Flavor", IsMeasuredByVolume=true },
                new Ingredient { Name="Anise", Calories=23, Type="Flavor", IsMeasuredByVolume=true },
                new Ingredient { Name="Cardamom", Calories=6, Type="Flavor", IsMeasuredByVolume=true },
                new Ingredient { Name="Peppermint", Calories=3, Type="Flavor", IsMeasuredByVolume=true },
                new Ingredient { Name="Almond Extract", Calories=1, Type="Flavor", IsMeasuredByVolume=true },
                new Ingredient { Name="Lemon Zest", Calories=2, Type="Flavor", IsMeasuredByVolume=true },
                new Ingredient { Name="Orange Zest", Calories=2, Type="Flavor", IsMeasuredByVolume=true },
                new Ingredient { Name="Lavender", Calories=1, Type="Flavor", IsMeasuredByVolume=true },
                new Ingredient { Name="Rosemary", Calories=1, Type="Flavor", IsMeasuredByVolume=true },
                new Ingredient { Name="Saffron", Calories=1, Type="Flavor", IsMeasuredByVolume=true },
                new Ingredient { Name="Miso", Calories=56, Type="Flavor", IsMeasuredByVolume=true },
                new Ingredient { Name="Soy Sauce", Calories=10, Type="Flavor", IsMeasuredByVolume=true },
                new Ingredient { Name="Worcestershire Sauce", Calories=13, Type="Flavor", IsMeasuredByVolume=true },
                new Ingredient { Name="Hot Sauce", Calories=5, Type="Flavor", IsMeasuredByVolume=true },
                new Ingredient { Name="Mustard", Calories=3, Type="Flavor", IsMeasuredByVolume=true },
                new Ingredient { Name="Horseradish", Calories=5, Type="Flavor", IsMeasuredByVolume=true },
                new Ingredient { Name="Peppermint Oil", Calories=0, Type="Essential Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Lemon Oil", Calories=0, Type="Essential Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Orange Oil", Calories=0, Type="Essential Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Lavender Oil", Calories=0, Type="Essential Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Eucalyptus Oil", Calories=0, Type="Essential Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Lime Oil", Calories=0, Type="Essential Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Ginger Oil", Calories=0, Type="Essential Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Rosemary Oil", Calories=0, Type="Essential Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Basil Oil", Calories=0, Type="Essential Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Cinnamon Oil", Calories=0, Type="Essential Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Clove Oil", Calories=0, Type="Essential Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Thyme Oil", Calories=0, Type="Essential Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Geranium Oil", Calories=0, Type="Essential Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Ylang-Ylang Oil", Calories=0, Type="Essential Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Tea Tree Oil", Calories=0, Type="Essential Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Frankincense Oil", Calories=0, Type="Essential Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Patchouli Oil", Calories=0, Type="Essential Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Cardamom Oil", Calories=0, Type="Essential Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Fennel Oil", Calories=0, Type="Essential Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Sandalwood Oil", Calories=0, Type="Essential Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Neroli Oil", Calories=0, Type="Essential Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Petitgrain Oil", Calories=0, Type="Essential Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Rose Oil", Calories=0, Type="Essential Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Violet Oil", Calories=0, Type="Essential Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Jasmine Oil", Calories=0, Type="Essential Oil", IsMeasuredByVolume=true },
                new Ingredient { Name="Vanilla Extract", Calories=12, Type="Extract", IsMeasuredByVolume=true },
                new Ingredient { Name="Almond Extract", Calories=6, Type="Extract", IsMeasuredByVolume=true },
                new Ingredient { Name="Lemon Extract", Calories=4, Type="Extract", IsMeasuredByVolume=true },
                new Ingredient { Name="Orange Extract", Calories=4, Type="Extract", IsMeasuredByVolume=true },
                new Ingredient { Name="Mint Extract", Calories=3, Type="Extract", IsMeasuredByVolume=true },
                new Ingredient { Name="Maple Extract", Calories=6, Type="Extract", IsMeasuredByVolume=true },
                new Ingredient { Name="Hazelnut Extract", Calories=8, Type="Extract", IsMeasuredByVolume=true },
                new Ingredient { Name="Coconut Extract", Calories=6, Type="Extract", IsMeasuredByVolume=true },
                new Ingredient { Name="Coffee Extract", Calories=1, Type="Extract", IsMeasuredByVolume=true },
                new Ingredient { Name="Butter Extract", Calories=10, Type="Extract", IsMeasuredByVolume=true },
                new Ingredient { Name="Caramel Extract", Calories=8, Type="Extract", IsMeasuredByVolume=true },
                new Ingredient { Name="Cherry Extract", Calories=5, Type="Extract", IsMeasuredByVolume=true },
                new Ingredient { Name="Raspberry Extract", Calories=5, Type="Extract", IsMeasuredByVolume=true },
                new Ingredient { Name="Ginger Extract", Calories=4, Type="Extract", IsMeasuredByVolume=true },
                new Ingredient { Name="Rose Extract", Calories=2, Type="Extract", IsMeasuredByVolume=true },
                new Ingredient { Name="Lavender Extract", Calories=3, Type="Extract", IsMeasuredByVolume=true },
                new Ingredient { Name="Pineapple Extract", Calories=6, Type="Extract", IsMeasuredByVolume=true },
                new Ingredient { Name="Cinnamon Extract", Calories=5, Type="Extract", IsMeasuredByVolume=true },
                new Ingredient { Name="Banana Extract", Calories=5, Type="Extract", IsMeasuredByVolume=true },
                new Ingredient { Name="Lemon Juice Concentrate", Calories=5, Type="Concentrate", IsMeasuredByVolume=true },
                new Ingredient { Name="Orange Juice Concentrate", Calories=15, Type="Concentrate", IsMeasuredByVolume=true },
                new Ingredient { Name="Lime Juice Concentrate", Calories=4, Type="Concentrate", IsMeasuredByVolume=true },
                new Ingredient { Name="Pineapple Juice Concentrate", Calories=30, Type="Concentrate", IsMeasuredByVolume=true },
                new Ingredient { Name="Apple Juice Concentrate", Calories=25, Type="Concentrate", IsMeasuredByVolume=true },
                new Ingredient { Name="Grape Juice Concentrate", Calories=59, Type="Concentrate", IsMeasuredByVolume=true },
                new Ingredient { Name="Tomato Paste Concentrate", Calories=82, Type="Concentrate", IsMeasuredByVolume=true },
                new Ingredient { Name="Coffee Concentrate", Calories=1, Type="Concentrate", IsMeasuredByVolume=true },
                new Ingredient { Name="Tea Concentrate", Calories=0, Type="Concentrate", IsMeasuredByVolume=true },
                new Ingredient { Name="Vanilla Concentrate", Calories=12, Type="Concentrate", IsMeasuredByVolume=true },
                new Ingredient { Name="Herb Extract Concentrate", Calories=2, Type="Concentrate", IsMeasuredByVolume=true },
                new Ingredient { Name="Mango Juice Concentrate", Calories=20, Type="Concentrate", IsMeasuredByVolume=true },
                new Ingredient { Name="Cranberry Juice Concentrate", Calories=46, Type="Concentrate", IsMeasuredByVolume=true },
                new Ingredient { Name="Raspberry Juice Concentrate", Calories=50, Type="Concentrate", IsMeasuredByVolume=true },
                new Ingredient { Name="Strawberry Juice Concentrate", Calories=50, Type="Concentrate", IsMeasuredByVolume=true },
                new Ingredient { Name="Coconut Milk Concentrate", Calories=180, Type="Concentrate", IsMeasuredByVolume=true },
                new Ingredient { Name="Pomegranate Juice Concentrate", Calories=83, Type="Concentrate", IsMeasuredByVolume=true },
                new Ingredient { Name="Cinnamon", Calories=6, Type="Spice", IsMeasuredByVolume=true },
                new Ingredient { Name="Clove", Calories=6, Type="Spice", IsMeasuredByVolume=true },
                new Ingredient { Name="Nutmeg", Calories=12, Type="Spice", IsMeasuredByVolume=true },
                new Ingredient { Name="Ginger", Calories=5, Type="Spice", IsMeasuredByVolume=true },
                new Ingredient { Name="Paprika", Calories=6, Type="Spice", IsMeasuredByVolume=true },
                new Ingredient { Name="Turmeric", Calories=8, Type="Spice", IsMeasuredByVolume=true },
                new Ingredient { Name="Cumin", Calories=8, Type="Spice", IsMeasuredByVolume=true },
                new Ingredient { Name="Cardamom", Calories=5, Type="Spice", IsMeasuredByVolume=true },
                new Ingredient { Name="Chili Powder", Calories=7, Type="Spice", IsMeasuredByVolume=true },
                new Ingredient { Name="Coriander", Calories=5, Type="Spice", IsMeasuredByVolume=true },
                new Ingredient { Name="Saffron", Calories=5, Type="Spice", IsMeasuredByVolume=true },
                new Ingredient { Name="Allspice", Calories=7, Type="Spice", IsMeasuredByVolume=true },
                new Ingredient { Name="Mustard Seed", Calories=20, Type="Spice", IsMeasuredByVolume=true },
                new Ingredient { Name="Fennel Seed", Calories=15, Type="Spice", IsMeasuredByVolume=true },
                new Ingredient { Name="Star Anise", Calories=23, Type="Spice", IsMeasuredByVolume=true },
                new Ingredient { Name="Tarragon", Calories=3, Type="Spice", IsMeasuredByVolume=true },
                new Ingredient { Name="Bay Leaf", Calories=1, Type="Spice", IsMeasuredByVolume=true },
                new Ingredient { Name="Chili Flakes", Calories=6, Type="Spice", IsMeasuredByVolume=true },
                new Ingredient { Name="Garlic Powder", Calories=5, Type="Spice", IsMeasuredByVolume=true },
                new Ingredient { Name="Onion Powder", Calories=8, Type="Spice", IsMeasuredByVolume=true },
                new Ingredient { Name="Black Pepper", Calories=6, Type="Spice", IsMeasuredByVolume=true },
                new Ingredient { Name="White Pepper", Calories=6, Type="Spice", IsMeasuredByVolume=true },
                new Ingredient { Name="Green Peppercorn", Calories=6, Type="Spice", IsMeasuredByVolume=true },
                new Ingredient { Name="Pink Peppercorn", Calories=6, Type="Spice", IsMeasuredByVolume=true },
                new Ingredient { Name="Szechuan Peppercorn", Calories=10, Type="Spice", IsMeasuredByVolume=true },
                new Ingredient { Name="Cayenne Pepper", Calories=5, Type="Spice", IsMeasuredByVolume=true },
                new Ingredient { Name="Paprika (Hot)", Calories=6, Type="Spice", IsMeasuredByVolume=true },
                new Ingredient { Name="Jalapeño Powder", Calories=6, Type="Spice", IsMeasuredByVolume=true },
                new Ingredient { Name="Chipotle Powder", Calories=6, Type="Spice", IsMeasuredByVolume=true },
                new Ingredient { Name="Ancho Chili Powder", Calories=8, Type="Spice", IsMeasuredByVolume=true },
                new Ingredient { Name="Agar-Agar", Calories=0, Type="Other", IsMeasuredByVolume=true },
                new Ingredient { Name="Xanthan Gum", Calories=7, Type="Other", IsMeasuredByVolume=true },
                new Ingredient { Name="Lecithin", Calories=30, Type="Other", IsMeasuredByVolume=true },
                new Ingredient { Name="Sodium Alginate", Calories=0, Type="Other", IsMeasuredByVolume=true },
                new Ingredient { Name="Calcium Chloride", Calories=0, Type="Other", IsMeasuredByVolume=true },
                new Ingredient { Name="Gellan Gum", Calories=0, Type="Other", IsMeasuredByVolume=true },
                new Ingredient { Name="Silica Gel (Food Grade)", Calories=0, Type="Other", IsMeasuredByVolume=false },
                new Ingredient { Name="Gelatin Sheets", Calories=23, Type="Other", IsMeasuredByVolume=true },
                new Ingredient { Name="Food-Grade Titanium Dioxide", Calories=0, Type="Other", IsMeasuredByVolume=true },
                new Ingredient { Name="Edible Gold Leaf", Calories=0, Type="Other", IsMeasuredByVolume=false },
                new Ingredient { Name="Caviar", Calories=240, Type="Other", IsMeasuredByVolume=false },
                new Ingredient { Name="Truffle Oil", Calories=120, Type="Other", IsMeasuredByVolume=true },
                new Ingredient { Name="Wasabi Powder", Calories=25, Type="Other", IsMeasuredByVolume=true },
                new Ingredient { Name="Citric Acid", Calories=0, Type="Other", IsMeasuredByVolume=true },
                new Ingredient { Name="Sodium Benzoate", Calories=0, Type="Other", IsMeasuredByVolume=true },
                new Ingredient { Name="Potassium Sorbate", Calories=0, Type="Other", IsMeasuredByVolume=true },
                new Ingredient { Name="Honey Powder", Calories=350, Type="Other", IsMeasuredByVolume=true },
                new Ingredient { Name="Agave Nectar", Calories=60, Type="Other", IsMeasuredByVolume=true },
                new Ingredient { Name="Truffle Oil", Calories=120, Type="Other", IsMeasuredByVolume=true },
                new Ingredient { Name="Garlic Oil", Calories=120, Type="Other", IsMeasuredByVolume=true },
                new Ingredient { Name="Chili Oil", Calories=120, Type="Other", IsMeasuredByVolume=true },
                new Ingredient { Name="Vegetable Stock Powder", Calories=15, Type="Other", IsMeasuredByVolume=true },
                new Ingredient { Name="Preserved Lemon", Calories=12, Type="Other", IsMeasuredByVolume=true },
                new Ingredient { Name="Smoked Salt", Calories=0, Type="Other", IsMeasuredByVolume=true },
                new Ingredient { Name="Marshmallow Fluff", Calories=40, Type="Other", IsMeasuredByVolume=true }
            };

            return ingredients.OrderBy(c => c.Type).ThenBy(c => c.Name).ToList();
        }
    }
}
